### ISSUE TITLE
Publish 1.2 to maven

### ISSUE THREAD

**Issue by eatonphil** [fgiannesini/LibSassGradlePlugin#1]
Hey! I am new to gradle, but I think your version 1.2 with the latest jsass support is not available to download via the maven repositories right now. [Here](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.github.fgiannesini.libsass.gradle.plugin%22) is a search result on search.maven.org that lists only versions 1.0 and 1.1.

In the meantime, I will try to use master on Github as the source.

**Comment by fgiannesini** [comment]
Hey !

Sorry, version 1.2 is not finished and as far as i remember, master has troubles. I recommend you to use 1.1 or to fork from 1.1.

Maybe i can help if you have questions or needs

**Comment by fgiannesini** [comment]
Version 1.2 is published to maven repositories with last jsass version (5.3.1)
