### ISSUE TITLE
Findbugs code analysis fails with "Possible null pointer dereference"

### ISSUE THREAD

**Issue by matschmann** [fgiannesini/LibSassGradlePlugin#2]
During build, findbugs code analysis generates the following error: 

Bug type NP_NULL_ON_SOME_PATH_FROM_RETURN_VALUE
In method com.github.fgiannesini.libsass.gradle.plugin.installer.ScssFrameworkInstallerTest.copySourcesToInstallationPath()

See attachment for full error report

[FindBugs Report.pdf](https://github.com/fgiannesini/LibSassGradlePlugin/files/633298/FindBugs.Report.pdf)

**Comment by fgiannesini** [comment]
Ok, i'll correct it on next commit

**Comment by fgiannesini** [comment]
FindBugs is now Ok
