### ISSUE TITLE
Test failure "LibSassCompilerTest.java:186"

### ISSUE THREAD

**Issue by matschmann** [fgiannesini/LibSassGradlePlugin#3]
The following test fails: 

com.github.fgiannesini.libsass.gradle.plugin.compiler.LibSassCompilerTest > writeCss_IOException FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at LibSassCompilerTest.java:186

**Comment by fgiannesini** [comment]
Sorry, i don't have the problem on mylocal environment

**Comment by matschmann** [comment]
I'll have a look at it

**Comment by matschmann** [comment]
Are you using a windows environment to build this project? 
I think the test `com.github.fgiannesini.libsass.gradle.plugin.compiler.LibSassCompilerTest#writeCss_IOException` just checks, if the file-api throws an exception, if the filename contains a '?', which is a forbidden character for file names in windows (see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx). On unix-system it is possible to create files with a ? in it. 
I think, this test is not necessary, because you are just testing code from the Apache Commons FileUtil-API.

**Comment by fgiannesini** [comment]
Using '/' character instead of '?'
